### ISSUE TITLE
Problems with Bean+

### ISSUE THREAD

**Issue by lawrie** [jacobrosenthal/ble-bean#24]
I am using a Raspberry Pi 2 and a Bean+ that I have just received from Kickstarter. I am running bean_example.js. It sometimes works, but only if I switch the Bean+ off and on again. More often, it hangs after getting the message:  noble: unknown peripheral 987bf3591a37 connected! 

After getting that message, switching the Bean+ off and on halts the program with no output.

Sometimes it detects the Bean+, but says it cannot find the advertised service: 
Error: service uuid a495ff10c5b14b44b5121370f02d74de not found!

Sometimes, when I switch the Bean+ on, the program just returns with no output.

(I started off using the node-red node, but that was even more unreliable due to these problems).

Has anyone else tried this code with a Bean+?

**Comment by f1erro** [comment]
have you opened up the bean loader and scanned for the bean?  What does it say?

**Comment by jacobrosenthal** [comment]
I dont have any bean+ and Im not really supporting this atm so its up to
you all reading this. Will merge PRs if you guys can verify fixes. And
happy to add contributors as well.

**Comment by lawrie** [comment]
I do have a general problem with my Bean+ which I have reported on the Beantalk forums and on Kickstarter: the device is only discoverable when you first switch it on.  That explains why I have to switch it on and off to connect to it. Apart from that the Android Bean Loader works and correctly recognises the Bean+.  The discovery problem could be the source of all the problems but it does not seem likely that it is causing the device to be wrongly recognised. I will investigate further and see if I can find a solution.
