### ISSUE TITLE
Mulitple Beans?

### ISSUE THREAD

**Issue by rossb93** [jacobrosenthal/ble-bean#9]
If you want to read data from multiple beans, how would this be possible. I understand this can't be done simultaneously but how could I switch from one Bean to another? Sorry if this is the wrong place to ask this.

Would this check need to be done in Bean.js?

YourThing.is = function(peripheral) {
  return (peripheral.advertisement.localName === 'My Thing\'s Name');
};

**Comment by jacobrosenthal** [comment]
Probably you need to change the example to store an array of beans and as
you connect them add them to the array.

@zgiles wrote some code to do this. Perhaps he talk about it, or update it
to the new API and pull request it as a multi bean example?

**Comment by rossb93** [comment]
@jacobrosenthal @zgiles A multi bean example would be great, using a raspberry pi as a server and I have two beans to read data from.

**Comment by zgiles** [comment]
I'd be happy to add the example to some repo or to just push it to my
github and people can pull it in if they'd like, whatever is preferred. I'd
recall it this evening.

On Tue, Jan 6, 2015 at 4:40 PM, rossb93 <notifications@github.com> wrote:

> @jacobrosenthal <https://github.com/jacobrosenthal> @zgiles
> <https://github.com/zgiles> A multi bean example would be great, using a
> raspberry pi as a server and I have two beans to read data from.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacobrosenthal/ble-bean/issues/9#issuecomment-68938867>
> .
>



-- 
Zach Giles
zgiles@gmail.com

**Comment by jacobrosenthal** [comment]
@zgiles notice the recent update. The API is almost entirely the same but
the setup procedure is vastly different as we implement the new Noble
Device. Youll have to reimplement into the new example.

**Comment by rossb93** [comment]
@jacobrosenthal, So @zgiles original example would require updating to the new API before it would be usable?
